In [2]:
import pandas as pd
import numpy as np
from collections import Counter

In [2]:
df = pd.read_csv("fruit_data_with_colors.txt",delimiter = "\t")

In [3]:
df.head()

fruit_label fruit_name fruit_subtype  mass  width  height  color_score
0            1      apple  granny_smith   192    8.4     7.3         0.55
1            1      apple  granny_smith   180    8.0     6.8         0.59
2            1      apple  granny_smith   176    7.4     7.2         0.60
3            2   mandarin      mandarin    86    6.2     4.7         0.80
4            2   mandarin      mandarin    84    6.0     4.6         0.79

In [4]:
X = df[["mass","width","height"]]

In [5]:
Y = df["fruit_label"]

In [6]:
trainX = np.array(X[:50])
trainY = np.array(Y[:50])
testX = np.array(X[50:])
testY = np.array(Y[50:])


In [7]:
class KNN:
    def __init__(self,k = 1):
        self.k = k
        
    def euclidian_distance(self,query,X):
        difference = np.array(X) - np.array(query)
        sqrd_diff = np.square(difference)
        sum_sqrd_diff = np.sum(sqrd_diff, axis = 1)
        distance = np.sqrt(sum_sqrd_diff)
        return distance
    
    def nearest_neighbours(self,distance):
        return np.argsort(distance)[:self.k]
    
    def predict(self,query,trainX,trainY):
        ed = self.euclidian_distance(query,trainX)
        nn = self.nearest_neighbours(ed)
        labels_nn = list(trainY[nn])
        return max(labels_nn, key = labels_nn.count) 
    

In [19]:
classifier = KNN(4)

In [20]:
predictions = [classifier.predict(x,trainX,trainY) for x in testX]

In [21]:
predictions

[3, 3, 3, 3, 3, 3, 3, 3, 3]

In [15]:
testY

array([4, 4, 4, 4, 4, 4, 4, 4, 4])

In [200]:
if __name__ == "__main__":
    print("hello")

hello


In [4]:
df = pd.read_csv("fruit_data_with_colors.txt",delimiter = "\t")

In [12]:
X = np.array(df[["mass","width","height","color_score"]])

In [16]:
X.shape

(59, 4)

# STEP 1

In [42]:
K = 4

# STEP 2

In [22]:
centroidIndex = np.random.randint(0,58,(4,))

In [43]:
centroidIndex

array([16, 41, 56, 25])

In [24]:
centroids = X[centroidIndex]

In [25]:
centroids

array([[1.00e+03, 7.60e+00, 7.50e+00, 6.70e-01],
       [1.80e+02, 7.60e+00, 8.20e+00, 7.90e-01],
       [1.16e+02, 5.90e+00, 8.10e+00, 7.30e-01],
       [3.56e+02, 9.20e+00, 9.20e+00, 7.50e-01]])

In [30]:
X_ = np.delete(X,centroidIndex, axis = 0)

In [50]:
clusters = [[],[],[],[]]
clusters[0].append(centroids[0])
clusters[1].append(centroids[1])
clusters[2].append(centroids[2])
clusters[3].append(centroids[3])


# STEP 3

In [51]:
def euclidian_distance(query,X):
        difference = np.array(X) - np.array(query)
        sqrd_diff = np.square(difference)
        sum_sqrd_diff = np.sum(sqrd_diff, axis = 1)
        distance = np.sqrt(sum_sqrd_diff)
        return distance

In [53]:
for x in X_:
    id = np.argmin(euclidian_distance(x,centroids))
    clusters[id].append(x)

In [61]:
len(clusters[0])

2

In [58]:
len(clusters[1])

37

In [59]:
len(clusters[2])

17

In [60]:
len(clusters[3])

3

In [65]:
centroids[0] = np.mean(clusters[0],axis = 0)