In [113]:
import pandas as pd
import numpy as np
from sklearn.metrics import log_loss

In [114]:
x = np.array([[0, 0],[0, 1],[1, 0],[1, 1]])

In [115]:
x

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [116]:
y = np.array([0, 1, 1, 0])

In [117]:
y

array([0, 1, 1, 0])

In [118]:
x.shape

(4, 2)

In [119]:
y.shape

(4,)

In [120]:
x = x.T

In [121]:
x.shape

(2, 4)

In [122]:
y = y.T

In [123]:
y.shape

(4,)

In [124]:
def sigmoid(z):
        return 1/(1 + np.exp(-z))

In [143]:
w = np.random.rand(2, 1)
b = np.random.rand()

alpha = 0.1

for i in range(60):
    z = np.dot(w.T, x) + b
    z = sigmoid(z)
    z = np.where(z < 0.5, 0, 1)
    z = z.squeeze()
    
    j = log_loss(y, z)
    print(j)
    if j < 10 :
        break
        
    dz = z- y
    dz = np.expand_dims(dz, axis=0)
    dw =  np.dot(x,dz.T)/4
    db = np.sum(dz)/4
    
    w = w - alpha * dw
    b = b - alpha * db
    
    

17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
8.63489399808522


In [145]:
z

array([0, 1, 1, 1])

In [146]:
y

array([0, 1, 1, 0])